# Site Settings
lang: "en"
timezone: "UTC"
show_downloads: false
theme: jekyll-theme-time-machine
google_analytics:  # Replace with Google Analytics ID

footer_left: "© 2025 IndieSpaceViking"
footer_right: "Privacy Policy"

# Exclude & Include
#exclude:
#  - README.md
#  - LICENSE
#  - Gemfile
#  - Gemfile.lock
#include:
#  - _pages
